/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'HeaderMenu.component': typeof import('./src/components/HeaderMenu.component.vue')['default']
    'LoginForm.component': typeof import('./src/components/forms/LoginForm.component.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPage: typeof import('naive-ui')['NPage']
    NPageBody: typeof import('naive-ui')['NPageBody']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    'RegisterForm.component': typeof import('./src/components/forms/RegisterForm.component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
